"""
Django settings for anamikapulses project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0-n!z^1_gydyrgygv$bvw33lcy3-3%kx9pny=xa4wijye5qx06'

try:
    ANAMIKAPULSES_ENV = os.environ['ANAMIKAPULSES_ENV']
    ANAMIKAPULSES_SECRET_KEY = os.environ['ANAMIKAPULSES_SECRET_KEY']
    ANAMIKAPULSES_DB_NAME = os.environ['ANAMIKAPULSES_DB_NAME']
    ANAMIKAPULSES_DB_USER = os.environ['ANAMIKAPULSES_DB_USER']
    ANAMIKAPULSES_DB_PASSWORD = os.environ['ANAMIKAPULSES_DB_PASSWORD']
    ANAMIKAPULSES_DB_HOST = os.environ['ANAMIKAPULSES_DB_HOST']
    ANAMIKAPULSES_ALLOWED_HOSTS = os.environ['ANAMIKAPULSES_ALLOWED_HOSTS']
   
except Exception as e:
    print(f"{str(e)}")
    exit()




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'assets',
    'ckeditor',
    'filer',
    'easy_thumbnails',
    'meta',
    'treebeard',
    'django_recaptcha',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'anamikapulses.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'assets', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'anamikapulses.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': ANAMIKAPULSES_DB_NAME,
            'USER': ANAMIKAPULSES_DB_USER,
            'PASSWORD': ANAMIKAPULSES_DB_PASSWORD,
            'HOST': ANAMIKAPULSES_DB_HOST,
            'PORT': '5432',
        }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Ck - Editor settings
CKEDITOR_CONFIGS = {
    'default': {
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'extraAllowedContent': (
            'div(class=*,col-md-*,container-fluid,\
                                row,tabpanel,tab-pane),\
                                *[id], *',
        )
    },
}

CKEDITOR_UPLOAD_PATH = "uploads/"

# Captcha
RECAPTCHA_PUBLIC_KEY = '6Lcnx0opAAAAAE3tVWDNYxVI9eXRWbM8LoARoobN'
RECAPTCHA_PRIVATE_KEY = '6Lcnx0opAAAAAMFemjSUXMMISJxIADJpoB8ru39n'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com.'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "testingonly552@gmail.com"
EMAIL_HOST_PASSWORD = "lgkyoymwmsdxoxqe"
FROM_EMAIL = "testingonly552@gmail.com"

CONTACTUS_FROM_EMAIL = "Bagmane Groups <enquiries@bagmanegroup.com>"
CONTACTUS_TO_ADMIN_EMAIL = ["aakash@webenza.com","tapan@webenza.com"]  #[marketing@bagmanegroup.com]
CAREER_FROM_EMAIL = "Careers - Bagmane Group  <careers@bagmanegroup.com>"
CAREER_TO_ADMIN_EMAIL = ["aakash@webenza.com","tapan@webenza.com"] #[hr@bagmanegroup.com]
PROPERTY_TO_ADMIN_EMAIL = ["aakash@webenza.com","tapan@webenza.com"]  #[marketing@bagmanegroup.com]
SUBSCRIBE_TO_ADMIN_EMAIL = ["aakash@webenza.com"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, os.path.join(DATA_DIR, 'assets/media'))
STATIC_ROOT = os.path.join(DATA_DIR, os.path.join(DATA_DIR, 'assets/static'))



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


