# Generated by Django 3.2.25 on 2024-10-01 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homestatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('section_one', ckeditor.fields.RichTextField(blank=True)),
                ('section_two', ckeditor.fields.RichTextField(blank=True)),
                ('section_three', ckeditor.fields.RichTextField(blank=True)),
                ('section_four', ckeditor.fields.RichTextField(blank=True)),
                ('section_five', ckeditor.fields.RichTextField(blank=True)),
                ('section_contact', ckeditor.fields.RichTextField(blank=True)),
                ('location_map', ckeditor.fields.RichTextField(blank=True)),
                ('location_address', ckeditor.fields.RichTextField(blank=True)),
                ('header', ckeditor.fields.RichTextField(blank=True)),
                ('footer', ckeditor.fields.RichTextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, default='Anamika Pulses', max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('other_meta_tags', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
