# Generated by Django 3.2.25 on 2024-10-01 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Please enter only letters.')])),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s\\.]*$', 'Please enter only alphanumeric characters.')])),
                ('published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contactus',
                'verbose_name_plural': 'contactus',
            },
        ),
    ]
