# Generated by Django 3.2.25 on 2024-10-01 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area Of Interest',
                'verbose_name_plural': 'Area Of Interest',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Please enter only letters.')])),
                ('email_id', models.EmailField(max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Please enter only numbers.')])),
                ('area_of_interest', models.CharField(max_length=80)),
                ('message', models.TextField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s\\.]*$', 'Please enter only alphanumeric characters.')])),
                ('document', models.FileField(upload_to='uploads/Careers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
